# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include: [ main, develop, release/* ]
pr:
  branches:
    include: [ main, develop]

pool: 
  name: home-office

steps:
  - checkout: self
    fetchDepth: 0

  - powershell: |
      $ErrorActionPreference = 'Stop'
      git config user.name "Azure DevOps"
      git config user.email "build@azuredevops.local"

      $remoteUrl = "https://$(GITHUB_USER):$(GITHUB_PAT)@github.com/$(GITHUB_OWNER)/$(GITHUB_REPO).git"

      git remote set-url github $remoteUrl 2>$null
      if ($LASTEXITCODE -ne 0) {
        git remote add github $remoteUrl
      }

      $branch = "$(Build.SourceBranchName)"
      Write-Host "Pushing branch $branch to $(GITHUB_REPO)..."
      git push github "HEAD:refs/heads/$branch" --force-with-lease
    displayName: 'Mirror to GitHub'