# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Azure Repos -> GitHub sync, por rama que dispara el build (sin force)
trigger:
  branches:
    include: [ main, develop, release/*, feature/* ]
  tags:
    include: [ 'v*' ]
pr: none

pool:
  name: home-office   # tu agente self-hosted

variables:
  GITHUB_OWNER: $(GITHUB_USER)
  GITHUB_REPO: barriolink-backend

steps:
- checkout: self
  fetchDepth: 0

- powershell: |
    $ErrorActionPreference = 'Stop'

    # --- Identificar qué disparó el build
    $ref        = $env:BUILD_SOURCEBRANCH        # p.ej. refs/heads/feature/x o refs/tags/v1.2.3
    $refName    = $env:BUILD_SOURCEBRANCHNAME    # p.ej. feature/x o v1.2.3
    $isTag      = $ref.StartsWith('refs/tags/')
    $isBranch   = $ref.StartsWith('refs/heads/')

    git --version
    git config user.name  "ci-mirror"
    git config user.email "ci-mirror@example.com"
    # Evitar choques con helpers del agente
    git config --global credential.helper ""

    # Remoto efímero a GitHub con PAT (Azure enmascara secretos en logs)
    git remote remove github 2>$null
    $remote = "https://$(GITHUB_USER):$(GITHUB_PAT)@github.com/$(GITHUB_OWNER)/$(GITHUB_REPO).git"
    git remote add github $remote

    git fetch --all --tags

    if ($isBranch) {
      Write-Host "== Sincronizando rama '$refName' a GitHub (sin force)"
      # Empujar el commit actual (HEAD) a la rama correspondiente en GitHub
      git push github HEAD:refs/heads/$refName
      if ($LASTEXITCODE -ne 0) {
        throw "Push a rama '$refName' falló. ¿Historia divergente o branch protection?"
      }

      # Enviar tags (no-forzado); útil si haces releases desde esta rama
      git push github --tags
      if ($LASTEXITCODE -ne 0) {
        throw "Push de tags falló."
      }

      # Verificación: comparar SHAs local vs remoto
      $localSha  = (git rev-parse HEAD)
      $remoteSha = (git ls-remote github "refs/heads/$refName" | ForEach-Object { $_.Split("`t")[0] })
      Write-Host "Local:  $localSha"
      Write-Host "Remote: $remoteSha"
      if (-not $remoteSha -or $remoteSha -ne $localSha) {
        throw "El commit remoto no coincide con el local tras el push."
      }
      Write-Host "OK: rama '$refName' sincronizada."
    }
    elseif ($isTag) {
      Write-Host "== Sincronizando tag '$refName' a GitHub"
      git push github $ref:$ref
      if ($LASTEXITCODE -ne 0) { throw "Push del tag '$refName' falló." }
      Write-Host "OK: tag '$refName' sincronizado."
    }
    else {
      throw "Tipo de ref no soportado: $ref"
    }
  displayName: 'Sync Azure → GitHub (rama actual + tags)'