# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include: [ main, develop, release/*, feature/* ]
  tags:
    include: [ 'v*' ]
pr: none

pool: 
  name: home-office
  #vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0

- powershell: |
    $ErrorActionPreference = 'Stop'
    git config user.name  "ci-mirror"
    git config user.email "ci-mirror@example.com"

    # Construye Authorization: Basic <base64(user:token)> sin exponer el PAT
    $pair = "$(GITHUB_USER):$(GITHUB_PAT)"
    $bytes = [System.Text.Encoding]::ASCII.GetBytes($pair)
    $b64  = [System.Convert]::ToBase64String($bytes)

    $url  = "https://github.com/DalizC/barriolink-backend.git"

    # Espejo no destructivo: crea/actualiza ramas y tags
    git -c http.extraheader="Authorization: Basic $b64" push $url --all
    git -c http.extraheader="Authorization: Basic $b64" push $url --tags
  displayName: 'Mirror to GitHub (DalizC/barriolink-backend)'
