# Generated by Django 5.2.7 on 2025-10-24 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='interval',
            new_name='duration',
        ),
    ]
