# Generated by Django 5.2.7 on 2025-10-24 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_location_url_event_address_url_event_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='owner',
            new_name='user',
        ),
    ]
