# Generated by Django 5.2.7 on 2025-10-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_owner_space_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('registered', 'Usuario Registrado'), ('member', 'Miembro'), ('admin', 'Administrador')], default='registered', max_length=20),
        ),
    ]
