# Generated by Django 5.2.7 on 2025-10-31 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_space_to_facility_add_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date', 'title']},
        ),
    ]
