# Generated by Django 5.2.7 on 2025-11-19 04:22

import django.db.models.deletion
from django.db import migrations, models


def create_default_tenant(apps, schema_editor):
    """Crear un tenant por defecto para migración de datos existentes."""
    Tenant = apps.get_model('core', 'Tenant')
    Tenant.objects.update_or_create(
        id=1,
        defaults={
            "name": "Barrio Principal",
            "slug": "barrio-principal",
            "address": "Calle Falsa 123, Viña del Mar, Chile",
            "contact_email": "",
            "contact_phone": "",
            "is_active": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del barrio o junta de vecinos', max_length=255)),
                ('national_id', models.CharField(blank=True, help_text='RUT, Tax ID, o identificador nacional', max_length=50)),
                ('slug', models.SlugField(help_text='Identificador único en URL', unique=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(create_default_tenant, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='booking',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='core.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='core.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(default=1, help_text='Barrio/Comunidad al que pertenece el usuario', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, help_text='RUT, DNI, o identificador nacional', max_length=50),
        ),
    ]
