# Generated by Django 5.2.7 on 2025-11-19 04:49

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tenant_booking_tenant_certificate_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='national_id',
            field=models.CharField(blank=True, help_text='RUT, Tax ID, o identificador nacional', max_length=50, validators=[core.validators.validate_national_id_format]),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, help_text='RUT, DNI, o identificador nacional', max_length=50, validators=[core.validators.validate_national_id_format]),
        ),
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Barrio/Comunidad al que pertenece el usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.tenant'),
        ),
    ]
