# Generated by Django 5.2.8 on 2025-11-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='news_items', to='core.category'),
        ),
    ]
