# Generated by Django 5.2.8 on 2025-11-25 02:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_news_published_news_archived_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(blank=True, help_text='Nombre del participante (si difiere del usuario)', max_length=255)),
                ('participant_email', models.EmailField(blank=True, help_text='Email de contacto del participante', max_length=254)),
                ('participant_phone', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de confirmación'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('waitlist', 'Lista de espera')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales o comentarios')),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, help_text='Monto a pagar (0 = gratuito) - preparado para futuro', max_digits=10)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Fecha de confirmación', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at', '-start_datetime'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='event',
            name='auto_confirm_registration',
            field=models.BooleanField(default=True, help_text='Si True: confirmación automática. Si False: requiere aprobación manual'),
        ),
        migrations.AddField(
            model_name='event',
            name='cost_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto del evento (0 = gratuito)', max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='cost_currency',
            field=models.CharField(default='CLP', help_text='Moneda (CLP, USD, etc.)', max_length=3),
        ),
        migrations.AddField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de fin del evento (opcional para eventos sin hora de fin definida)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='has_cost',
            field=models.BooleanField(default=False, help_text='Si el evento tiene costo (futuro: integración de pagos)'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si el evento está activo/visible'),
        ),
        migrations.AddField(
            model_name='event',
            name='members_only',
            field=models.BooleanField(default=False, help_text='Si True: solo usuarios con rol member pueden inscribirse'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_days_of_week',
            field=models.CharField(blank=True, help_text='Días de la semana para recurrencia semanal (ej: "1,3,5" para L-M-V)', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_end_date',
            field=models.DateField(blank=True, help_text='Fecha hasta la cual se repite el evento (solo si tiene recurrencia)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_interval',
            field=models.IntegerField(default=1, help_text='Intervalo de recurrencia (ej: cada 2 semanas para bisemanal)'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_type',
            field=models.CharField(choices=[('none', 'Evento único'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('biweekly', 'Bisemanal'), ('monthly', 'Mensual'), ('custom', 'Personalizado')], default='none', help_text='Tipo de recurrencia del evento', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, help_text='Fecha límite para inscribirse (si no se especifica, hasta el inicio del evento)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='requires_registration',
            field=models.BooleanField(default=False, help_text='Si el evento requiere inscripción previa'),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug autogenerado a partir del título', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de inicio del evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='amenities',
            field=models.TextField(blank=True, help_text='Lista libre de comodidades, una por línea'),
        ),
        migrations.AddField(
            model_name='facility',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug autogenerado a partir del nombre', max_length=255),
        ),
        migrations.AddField(
            model_name='facility',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Si el evento es público o privado'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de aprobación'), ('scheduled', 'Programado'), ('cancelled', 'Cancelado'), ('completed', 'Completado')], default='pending', help_text='Estado del evento (PENDING requiere aprobación de admin)', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(help_text='Usuario creador del evento', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('end_datetime__isnull', True), ('end_datetime__gt', models.F('start_datetime')), _connector='OR'), name='event_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('facility__isnull', True), ('end_datetime__isnull', False), _connector='OR'), name='event_facility_requires_end_datetime'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que confirmó la inscripción (si fue manual)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.event'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(help_text='Usuario inscrito al evento', on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'status'], name='core_eventr_event_i_a18f22_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['user', 'status'], name='core_eventr_user_id_589976_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'user')},
        ),
    ]
