# Generated by Django 5.2.8 on 2025-11-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_eventregistration_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrence_count',
            field=models.PositiveIntegerField(blank=True, help_text='Número de ocurrencias por periodo (ej: 2 veces a la semana)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_monthly_mode',
            field=models.CharField(blank=True, choices=[('day_of_week', 'Mantener día de la semana'), ('day_of_month', 'Mantener fecha fija')], help_text='Para recurrencia mensual: mantener día de la semana o fecha fija', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_times',
            field=models.JSONField(blank=True, help_text='Horarios individuales por ocurrencia: [{"day": 2, "start_time": "18:00", "end_time": "20:00"}, ...]', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='recurrence_interval',
            field=models.IntegerField(default=1, help_text='Intervalo de recurrencia (ej: cada 2 semanas)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='recurrence_type',
            field=models.CharField(choices=[('none', 'Evento único'), ('daily', 'Diaria'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('semestral', 'Semestral'), ('yearly', 'Anual')], default='none', help_text='Tipo de recurrencia del evento', max_length=20),
        ),
    ]
