# Generated by Django 5.2.8 on 2025-11-26 08:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_event_recurrence_count_event_recurrence_monthly_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.news_image_file_path),
        ),
    ]
