# Generated by Django 5.2.8 on 2025-11-26 13:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen representativa del evento', null=True, upload_to=core.models.event_image_file_path),
        ),
    ]
